spring:
    datasource:
      base:
        url: jdbc:mysql://localhost:3306/min?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username:
        password:
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        initialize: true


      base2:
        url: jdbc:mysql://localhost:3306/min?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username:
        password:
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        name: main2